### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Roozbeh2429** [anujpathania/HotSniper#4]
Hi, HotSniper is working well on Ubuntu 16.04. but on **Ubuntu 20.04.2 LTS** it seems that the **hotspot** has some problems.
It will be great if the HotSniper becomes functional on **Ubuntu 20.04** too. 

The error is:
`../hotspot/hotspot: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by ../hotspot/hotspot)`

Here is the first part of the console log:

```
I have no name!@60cd8fd785f0:/home/roozbeh/projects/HotSniper/simulationcontrol$ PYTHONIOENCODING="UTF-8" python3 run.py
running parsec-blackscholes-simsmall-15 with configuration 1.0GHz+maxFreq+slowDVFS
-n 64 -c gainestown --benchmarks=parsec-blackscholes-simsmall-15 --no-roi --sim-end=last -senergystats:1000000 -speriodic-power:1000000
[app0] [PARSEC] Benchmarks to run: blackscholes
[app0] 
[app0] [PARSEC] [========== Running benchmark blackscholes ==========]
[app0] [PARSEC] Setting up run directory.
[app0] [PARSEC] Unpacking benchmark input 'simsmall'.
[SNIPER] Start
[app0] in_4K.txt
[app0] [PARSEC] Running '/home/roozbeh/projects/HotSniper/record-trace --routine-tracing -o /tmp/tmpOOhgsO/run_benchmarks -e 1 -r 1 -s 0 -- /home/roozbeh/projects/HotSniper/benchmarks/parsec/parsec-2.1/pkgs/apps/blackscholes/inst/amd64-linux.gcc-sniper/bin/blackscholes 15 in_4K.txt prices.txt':
[app0] [PARSEC] [---------- Beginning of output ----------]
[Scheduler]: Setting Arrival Time for Task 0 (parsec-blackscholes-simsmall-15) to 0 ns
[Scheduler] [Info]: Initializing mapping policy
[Scheduler] [Info]: Initializing DVFS policy
Executing Python script /home/roozbeh/projects/HotSniper/benchmarks/sim.scripts.py

[Scheduler]: Trying to map Thread  0 from Task 0 at Time 0 ns

[Scheduler]: Trying to schedule Task 0 at Time 0 ns

[Scheduler]: Task 0 put into execution queue. 
[Scheduler]: Assigning Core 0 to Task 0
[Scheduler]: Assigning Core 1 to Task 0
[Scheduler]: Assigning Core 2 to Task 0
[Scheduler]: Assigning Core 3 to Task 0
[Scheduler]: Assigning Core 4 to Task 0
[Scheduler]: Assigning Core 5 to Task 0
[Scheduler]: Assigning Core 6 to Task 0
[Scheduler]: Assigning Core 7 to Task 0
[Scheduler]: Assigning Core 8 to Task 0
[Scheduler]: Assigning Core 9 to Task 0
[Scheduler]: Assigning Core 10 to Task 0
[Scheduler]: Assigning Core 11 to Task 0
[Scheduler]: Assigning Core 12 to Task 0
[Scheduler]: Assigning Core 13 to Task 0
[Scheduler]: Assigning Core 14 to Task 0
[Scheduler]: Assigning Core 15 to Task 0

[Scheduler]: Setting Affinity for Thread 0 from Task 0 to Core 0

[SNIPER] --------------------------------------------------------------------------------
[SNIPER] Sniper using SIFT/trace-driven frontend
[SNIPER] Running full application in DETAILED mode
[SNIPER] --------------------------------------------------------------------------------
[SNIPER] Enabling performance models
[SNIPER] Setting instrumentation mode to DETAILED
[app0] PARSEC Benchmark Suite Version 2.1
[app0] [HOOKS] PARSEC Hooks Version 1.2

[Scheduler]: Time 1.000.000 ns [Active Tasks =  1 | Completed Tasks = 0 | Queued Tasks = 0 | Non-Queued Tasks  = 0 | Free Cores = 48 | Active Tasks Requirements = 16 ] 


[Scheduler]: DVFS Control Loop invoked at 1.000.000 ns
[Scheduler][DVFS_MAX_FREQ]: Core  0: P=0.547 W f=4000 MHz T=-1.0 °C utilization=0.372
[SNIPER] Setting frequency for core 0 in DVFS domain 0 to 1000 MHz
[SNIPER] Setting frequency for core 1 in DVFS domain 1 to 1000 MHz
[SNIPER] Setting frequency for core 2 in DVFS domain 2 to 1000 MHz
[SNIPER] Setting frequency for core 3 in DVFS domain 3 to 1000 MHz
[SNIPER] Setting frequency for core 4 in DVFS domain 4 to 1000 MHz
[SNIPER] Setting frequency for core 5 in DVFS domain 5 to 1000 MHz
[SNIPER] Setting frequency for core 6 in DVFS domain 6 to 1000 MHz
[SNIPER] Setting frequency for core 7 in DVFS domain 7 to 1000 MHz
[SNIPER] Setting frequency for core 8 in DVFS domain 8 to 1000 MHz
[SNIPER] Setting frequency for core 9 in DVFS domain 9 to 1000 MHz
[SNIPER] Setting frequency for core 10 in DVFS domain 10 to 1000 MHz
[SNIPER] Setting frequency for core 11 in DVFS domain 11 to 1000 MHz
[SNIPER] Setting frequency for core 12 in DVFS domain 12 to 1000 MHz
[SNIPER] Setting frequency for core 13 in DVFS domain 13 to 1000 MHz
[SNIPER] Setting frequency for core 14 in DVFS domain 14 to 1000 MHz
[SNIPER] Setting frequency for core 15 in DVFS domain 15 to 1000 MHz
[SNIPER] Setting frequency for core 16 in DVFS domain 16 to 1000 MHz
[SNIPER] Setting frequency for core 17 in DVFS domain 17 to 1000 MHz
[SNIPER] Setting frequency for core 18 in DVFS domain 18 to 1000 MHz
[SNIPER] Setting frequency for core 19 in DVFS domain 19 to 1000 MHz
[SNIPER] Setting frequency for core 20 in DVFS domain 20 to 1000 MHz
[SNIPER] Setting frequency for core 21 in DVFS domain 21 to 1000 MHz
[SNIPER] Setting frequency for core 22 in DVFS domain 22 to 1000 MHz
[SNIPER] Setting frequency for core 23 in DVFS domain 23 to 1000 MHz
[SNIPER] Setting frequency for core 24 in DVFS domain 24 to 1000 MHz
[SNIPER] Setting frequency for core 25 in DVFS domain 25 to 1000 MHz
[SNIPER] Setting frequency for core 26 in DVFS domain 26 to 1000 MHz
[SNIPER] Setting frequency for core 27 in DVFS domain 27 to 1000 MHz
[SNIPER] Setting frequency for core 28 in DVFS domain 28 to 1000 MHz
[SNIPER] Setting frequency for core 29 in DVFS domain 29 to 1000 MHz
[SNIPER] Setting frequency for core 30 in DVFS domain 30 to 1000 MHz
[SNIPER] Setting frequency for core 31 in DVFS domain 31 to 1000 MHz
[SNIPER] Setting frequency for core 32 in DVFS domain 32 to 1000 MHz
[SNIPER] Setting frequency for core 33 in DVFS domain 33 to 1000 MHz
[SNIPER] Setting frequency for core 34 in DVFS domain 34 to 1000 MHz
[SNIPER] Setting frequency for core 35 in DVFS domain 35 to 1000 MHz
[SNIPER] Setting frequency for core 36 in DVFS domain 36 to 1000 MHz
[SNIPER] Setting frequency for core 37 in DVFS domain 37 to 1000 MHz
[SNIPER] Setting frequency for core 38 in DVFS domain 38 to 1000 MHz
[SNIPER] Setting frequency for core 39 in DVFS domain 39 to 1000 MHz
[SNIPER] Setting frequency for core 40 in DVFS domain 40 to 1000 MHz
[SNIPER] Setting frequency for core 41 in DVFS domain 41 to 1000 MHz
[SNIPER] Setting frequency for core 42 in DVFS domain 42 to 1000 MHz
[SNIPER] Setting frequency for core 43 in DVFS domain 43 to 1000 MHz
[SNIPER] Setting frequency for core 44 in DVFS domain 44 to 1000 MHz
[SNIPER] Setting frequency for core 45 in DVFS domain 45 to 1000 MHz
[SNIPER] Setting frequency for core 46 in DVFS domain 46 to 1000 MHz
[SNIPER] Setting frequency for core 47 in DVFS domain 47 to 1000 MHz
[SNIPER] Setting frequency for core 48 in DVFS domain 48 to 1000 MHz
[SNIPER] Setting frequency for core 49 in DVFS domain 49 to 1000 MHz
[SNIPER] Setting frequency for core 50 in DVFS domain 50 to 1000 MHz
[SNIPER] Setting frequency for core 51 in DVFS domain 51 to 1000 MHz
[SNIPER] Setting frequency for core 52 in DVFS domain 52 to 1000 MHz
[SNIPER] Setting frequency for core 53 in DVFS domain 53 to 1000 MHz
[SNIPER] Setting frequency for core 54 in DVFS domain 54 to 1000 MHz
[SNIPER] Setting frequency for core 55 in DVFS domain 55 to 1000 MHz
[SNIPER] Setting frequency for core 56 in DVFS domain 56 to 1000 MHz
[SNIPER] Setting frequency for core 57 in DVFS domain 57 to 1000 MHz
[SNIPER] Setting frequency for core 58 in DVFS domain 58 to 1000 MHz
[SNIPER] Setting frequency for core 59 in DVFS domain 59 to 1000 MHz
[SNIPER] Setting frequency for core 60 in DVFS domain 60 to 1000 MHz
[SNIPER] Setting frequency for core 61 in DVFS domain 61 to 1000 MHz
[SNIPER] Setting frequency for core 62 in DVFS domain 62 to 1000 MHz
[SNIPER] Setting frequency for core 63 in DVFS domain 63 to 1000 MHz
../hotspot/hotspot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ../hotspot/hotspot)
Traceback (most recent call last):
  File "/home/roozbeh/projects/HotSniper/tools/mcpat.py", line 1601, in <module>
    main(jobid = jobid, resultsdir = resultsdir, powertype = powertype, config = config, outputfile = outputfile, no_graph = no_graph, print_stack = not no_text, partial = partial)
  File "/home/roozbeh/projects/HotSniper/tools/mcpat.py", line 310, in main
    results = power_stack(power_dat,results['config'], powertype)
  File "/home/roozbeh/projects/HotSniper/tools/mcpat.py", line 616, in power_stack
    temperatures = subprocess.check_output([hotspot_binary] + hotspot_args)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['../hotspot/hotspot', '-c', '../hotspot/hotspot.config', '-f', '/home/roozbeh/projects/HotSniper/benchmarks/8x8_manycore.flp', '-sampling_intvl', '0.001', '-p', 'InstantaneousPower.log', '-o', 'InstantaneousTemperature.log']' returned non-zero exit status 1

[Scheduler]: Time 2.000.000 ns [Active Tasks =  1 | Completed Tasks = 0 | Queued Tasks = 0 | Non-Queued Tasks  = 0 | Free Cores = 48 | Active Tasks Requirements = 16 ] 


[Scheduler]: DVFS Control Loop invoked at 2.000.000 ns
[Scheduler][DVFS_MAX_FREQ]: Core  0: P=0.545 W f=1000 MHz T=-1.0 °C utilization=0.370
../hotspot/hotspot: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ../hotspot/hotspot)
```

**Comment by ma-rapp** [comment]
I guess you built HotSpot outside docker like described in the README. Could you try building hotspot inside docker?

**Comment by Roozbeh2429** [comment]
Dear Martin, the problem resolved by **building the hotspot inside the docker container**. thank you so much.

**Comment by ma-rapp** [comment]
I updated the README
